services:
  api:
    build: 
      context: ./api
    container_name: auto-ncore-api
    command: uvicorn main:app --host 0.0.0.0 --port 3000 --reload
    ports:
      - 3000:3000
    environment:
      - APP_ENV=development
    volumes:
      - ./api:/app
    depends_on:
      - transmission

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./frontend:/usr/share/nginx/html
  #   command: ["npm", "run", "build"]

  nginx:
    build:
      context: ./nginx
    ports: 
      - "85:80"
    depends_on:
      - api
      # - frontend
    volumes:
      - /tmp/mnt/Intenso/www:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  transmission:
    image: linuxserver/transmission:arm32v7-version-3.00-r8
    container_name: transmission
    ports:
      - "9091:9091"
      - "51516:51515"  # Change the external port (51516) to avoid conflict
      - "51516:51515/udp"  # Similarly, change the UDP port
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=admin
      - PASS=password
    volumes:
      - ./transmission:/config
      - ./downloads:/downloads
