services:
  backend:
    build: 
      context: ./backend
    container_name: auto-ncore-backend
    command: >
      python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 3000 --reload
    ports:
      - 3000:3000
      - 5678:5678
    env_file:
      - path: ./backend/.env
        required: true
    environment:
      - APP_ENV=development
    volumes:
      - ./backend:/app
    depends_on:
      - transmission

  frontend:
    build:
      context: ./frontend
    container_name: auto-ncore-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules # prevents overwriting
    depends_on:
      - backend

  # nginx:
  #   build:
  #     context: ./nginx
  #   container_name: auto-ncore-frontend
  #   ports: 
  #     - "85:80"
  #   depends_on:
  #     - backend
  #     # - frontend
  #   volumes:
  #     - /tmp/mnt/Intenso/www:/usr/share/nginx/html:ro
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    ports:
      - "9091:9091"
      - "52515:51515"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER=admin
      - PASS=password
    volumes:
      - ./transmission:/config
      - ./downloads:/downloads
