from infrastructure.ncore_client import NCoreClient
from infrastructure.config_service import ConfigService

def test_parse_tvshow_title() -> None:
    config_service = ConfigService()
    client = NCoreClient(config_service)
    
    test_cases = [
        {"case":"Friday Night Lights - Tiszta szívvel foci S01-S05", "result": "Friday Night Lights Tiszta szívvel foci" },
        {"case":"Tess of the D'Urbervilles S01", "result": ""},
        {"case":"A tisztaság ára S01", "result": ""},
        {"case":"Tiszta bűn S01", "result": ""},
        {"case":"Tess.of.the.D'Urbervilles.2008.S01.BDRip.x264.Hun-BNR", "result": ""},
        {"case":"Sparking.Joy.S01.NF.WEBRip.x264.HUN-FULCRUM", "result": ""},
        {"case":"Egyiptom tisztázatlan aktái S01", "result": ""},
        {"case":"Mao Mao - Tiszta Szív hősei S01 576p", "result": ""},
        {"case":"Piszkos pénz, tiszta szerelem S01", "result": ""},
        {"case":"Rossella - Egy tiszta szívű asszony S01 ", "result": ""},
        {"case":"Tiszta Hawaii S01", "result": ""},
        {"case":"Friday.Night.Lights.S02.HUN.DVDRip.XviD-HSF", "result": ""},
        {"case":"This.Fool.S02.1080p.WEB.h264-ETHEL", "result": ""},
        {"case":"Friday Night Lights - Tiszta szívvel foci S01-S05 1080p", "result": ""},
        {"case":"Friday Night Lights - Tiszta szívvel foci S05 720p", "result": ""},
        {"case":"Friday Night Lights - Tiszta szívvel foci S04 720p", "result": ""},
        {"case":"Friday Night Lights - Tiszta szívvel foci S03 720p", "result": ""},
        {"case":"Friday Night Lights - Tiszta szívvel foci S02 720p", "result": ""},
        {"case":"Friday Night Lights - Tiszta szívvel foci S01 720p", "result": ""},
        {"case":"Pure.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264.Hun-ARROW", "result": ""},
        {"case":"Pure.S01.720p.AMZN.WEB-DL.DDP5.1.H.264.Hun-ARROW", "result": ""},
        {"case":"Tabula.Rasa.S01.720p.NF.WEB-DL.DD5.1.x264.Hun-ARROW", "result": ""},
        {"case":"Tabula.Rasa.S01.1080p.NF.WEB-DL.DD5.1.x264.Hun-ARROW", "result": ""},
        {"case":"Spotless.S01.REPACK.1080p.DRTE.WEB-DL.AAC2.0.H.264.Hun-ARROW", "result": ""},
        {"case":"Spotless.S01.REPACK.720p.DRTE.WEB-DL.AAC2.0.H.264.Hun-ARROW", "result": ""},
        {"case":"Horizon.S54E01.Clean.Eating.The.Dirty.Truth.1080p.DAVI.WEB-DL.AAC2.0.H264.HuN.EnG-B9R", "result": ""},
        {"case":"Horizon.S54E01.Clean.Eating.The.Dirty.Truth.720p.DAVI.WEB-DL.AAC2.0.H264.HuN.EnG-B9R", "result": ""},
        {"case":"White.Famous.S01.720p.SKST.WEB-DL.DD+2.0.H.264.HUN-SLN", "result": ""},
        {"case":"White.Famous.S01.1080p.SKST.WEB-DL.DD+2.0.H.264.HUN-SLN", "result": ""},
        {"case":"Pandora.2019.S02.WEB.h264-BAE", "result": ""},
        {"case":"Bevándorlók Ausztráliában S01", "result": ""},
        {"case":"Pandora.2019.S01.MiXED.x264-MiXGROUP", "result": ""},
        {"case":"Andor.S02.DSNP.WEBRiP.AAC2.0.x264.HuN.EnG-B9R", "result": ""},
        {"case":"Bandidos.S01.2024.NF.WEBRiP.AAC2.0.x264.HuN.SpA-B9R", "result": ""},
        {"case":"Alexander.The.Making.of.a.God.S01.480p.NF.WEB-DL.DD+5.1.Atmos.H.264.Hun-ARROW", "result": ""},
        {"case":"Star.Wars.Andor.S01.HS.WEBRip.x264.HUN.ENG-FULCRUM", "result": ""},
        {"case":"Rocklexikon - Benkó Sándor", "result": ""},
        {"case":"Beforeigners.S02.HMAX.WEBRip.x264.HUN.NOR-FULCRUM", "result": ""},
        {"case":"Sandor.Matyas.1979.S01.Read.Nfo.ReTaiL.DVDRip.x264.Hun-eStone", "result": ""},
        {"case":"Vándorlás a természetben S01", "result": ""},
        {"case":"Vándorlás a természetben S01", "result": ""},
        {"case":"Beforeigners.S01.WEB-DLRip.x264.HUN-Teko", "result": ""},
        {"case":"Andor.S01E00.A.Disney.Day.Special.Look.1080p.WEB.h264-KOGi", "result": ""},
        {"case":"Pandora.2019.S02.720p.WEB.H264-MiXGROUP", "result": ""},
        {"case":"Bevándorlók Ausztráliában S01 1080p", "result": ""},
        {"case":"Bevándorlók Ausztráliában S01 720p", "result": ""},
        {"case":"Pandora.2019.S01.720p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS", "result": ""},
        {"case":"Időbevándorlók S01 720p", "result": ""},
        {"case":"Időbevándorlók S01 1080p", "result": ""},
        {"case":"Pandora of the Crimson Shell S01 720p", "result": ""},
        {"case":"Pandora Hearts S01 720p", "result": ""},
        {"case":"Star.Wars.Andor.S02.2160p.APPS.WEB-DL.DDP.Atmos.5.1.H.265.HuN-GOODWILL", "result": ""},
        {"case":"Star.Wars.Andor.S02E01.2160p.APPS.WEB-DL.DDP.Atmos.5.1.H.265.HuN-GOODWILL", "result": ""},
        {"case":"Andor.S02.1080p.DSNP.WEB-DL.DDP5.1.Atmos.DV.HDR.H265.HuN.EnG-B9R", "result": ""},
        {"case":"Star.Wars.Andor.S02.2160p.DSNP.WEB-DL.P5.Dolby.Vision.DDP5.1.Atmos.h265.HUN-UFO971", "result": ""},
        {"case":"Star.Wars.Andor.S02.2160p.DSNP.WEB-DL.DDP5.1.Atmos.DV.HDR.H.265.HUN.ENG-PTHD", "result": ""},
        {"case":"Star.Wars.Andor.S02.1080p.DSNP.WEB-DL.DDP5.1.Atmos.H.264.HUN.ENG-PTHD", "result": ""},
        {"case":"Star.Wars.Andor.S02.720p.DSNP.WEB-DL.DDP5.1.Atmos.H.264.HUN.ENG-PTHD", "result": ""},
        {"case":"Star.Wars.Andor.S01.2160p.DSNP.WEB-DL.P5.Dolby.Vision.DDP-Atmos.5.1.h265.HUN-UFO971", "result": ""},
        {"case":"Bandidos.S02.1080p.NF.WEB-DL.DV.HDR.DDP5.1.Atmos.H.265.HUN-FULCRUM", "result": ""},
        {"case":"Bandidos.S02.1080p.NF.WEB-DL.DDP5.1.Atmos.H.264.HUN-FULCRUM", "result": ""}
    ]
    
    for test_case in test_cases:
        assert client.parse_tvshow_title(test_case["case"] == test_case["result"])